[package]
name = "update"
version = "0.1.0"
authors = ["n7484443 <n7484443@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.2.0"